services:
  app:
    build: .
    container_name: tax-crawler-app
    restart: unless-stopped
    shm_size: 2g
    ports:
      - "8102:8102"
    environment:
      - HOST=0.0.0.0
      - PORT=8102
      - WORKERS=1
      - USE_REDIS=false
    volumes:
      - ./data:/app/data
      - /dev/shm:/dev/shm
    networks:
      - tax-crawler-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8102/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # (tùy chọn) tăng performance DNS và tránh latency
    network_mode: host

  redis:
    image: redis:7-alpine
    container_name: tax-crawler-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  tax-crawler-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
